services:
  postgres:
    image: postgres:16-alpine
    container_name: debitum-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DebitumDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: debitum-api
    restart: always
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Database__Postgres__ConnectionString: "Host=postgres;Port=5432;Database=DebitumDb;Username=postgres;Password=postgres"
    ports:
      - "5000:8080"

volumes:
  postgres_data:
